export const gameplayStyles = [
    'Stealth',
    'Turn-Based',
    'Turn-Based Combat',
    'Building',
    'Procedural Generation',
    'Tactical',
    'Open World',
    'Bullet Hell',
    'Walking Simulator',
    'Auto Battler',
    'Automation',
    'Choices Matter',
    'Exploration',
    'Deckbuilding',
    'Resource Management',
    'Arcade',
    'Narration',
    'Detective',
    'Dungeon Crawler',
    'Base Building',
    'Crafting',
    '2D Platformer',
    'Fast-Paced',
    'Clicker',
    'Point & Click',
    'Parkour',
    'Permadeath',
    'Real Time Tactics',
    'Time Management',
    'Turn-Based Tactics',
    'Driving',
];

export const themes = [
    'Fantasy',
    'Magic',
    'Drama',
    'Surreal',
    'War',
    'Historical',
    'Cyberpunk',
    'Thriller',
    'Supernatural',
    'Mythology',
    'Noir',
    'Medieval',
    'Space',
    'Futuristic',
    'Post-apocalyptic',
    'Superhero',
    'Sci-fi',
    'Romance',
    'Cute',
    'Retro',
    'Mystery',
    'Dark Fantasy',
    'Comedy',
    'Satire',
    'Psychological Horror',
    'Anime',
    'Crime',
];

export const moods = [
    'Atmospheric',
    'Relaxing',
    'Funny',
    'Emotional',
    'Psychological',
    'Violent',
    'Dark',
    'Cinematic',
    'Wholesome',
];
