export const gameplayStyles = [
    { tagid: 1687, name: 'Stealth' },
    { tagid: 14139, name: 'Turn-Based Tactics' },
    { tagid: 4325, name: 'Turn-Based Combat' },
    { tagid: 1643, name: 'Building' },
    { tagid: 5125, name: 'Procedural Generation' },
    { tagid: 1708, name: 'Tactical' },
    { tagid: 1695, name: 'Open World' },
    { tagid: 4885, name: 'Bullet Hell' },
    { tagid: 5900, name: 'Walking Simulator' },
    { tagid: 1084988, name: 'Auto Battler' },
    { tagid: 255534, name: 'Automation' },
    { tagid: 6426, name: 'Choices Matter' },
    { tagid: 3834, name: 'Exploration' },
    { tagid: 32322, name: 'Deckbuilding' },
    { tagid: 8945, name: 'Resource Management' },
    { tagid: 1773, name: 'Arcade' },
    { tagid: 8369, name: 'Investigation' },
    { tagid: 1720, name: 'Dungeon Crawler' },
    { tagid: 7332, name: 'Base Building' },
    { tagid: 1702, name: 'Crafting' },
    { tagid: 379975, name: 'Clicker' },
    { tagid: 1698, name: 'Point & Click' },
    { tagid: 4036, name: 'Parkour' },
    { tagid: 3813, name: 'Real Time Tactics' },
    { tagid: 16689, name: 'Time Management' },
    { tagid: 12472, name: 'Management' },
    { tagid: 14139, name: 'Turn-Based Tactics' },
    { tagid: 1644, name: 'Driving' },
    { tagid: 5094, name: 'Narration' },
    { tagid: 1775, name: 'PvP' },
    { tagid: 4486, name: 'Choose Your Own Adventure' },
    { tagid: 9204, name: 'Immersive Sim' },
    { tagid: 5652, name: 'Collectathon' },
    { tagid: 3854, name: 'Lore-Rich' },
    { tagid: 3878, name: 'Competitive' },
    { tagid: 3877, name: 'Precision Platformer' },
    { tagid: 1734, name: 'Fast-Paced' },
];

export const themes = [
    { tagid: 1684, name: 'Fantasy' },
    { tagid: 1710, name: 'Surreal' },
    { tagid: 1678, name: 'War' },
    { tagid: 3987, name: 'Historical' },
    { tagid: 4115, name: 'Cyberpunk' },
    { tagid: 4064, name: 'Thriller' },
    { tagid: 10808, name: 'Supernatural' },
    { tagid: 16094, name: 'Mythology' },
    { tagid: 6052, name: 'Noir' },
    { tagid: 4172, name: 'Medieval' },
    { tagid: 1755, name: 'Space' },
    { tagid: 4295, name: 'Futuristic' },
    { tagid: 3835, name: 'Post-apocalyptic' },
    { tagid: 1671, name: 'Superhero' },
    { tagid: 3942, name: 'Sci-fi' },
    { tagid: 4947, name: 'Romance' },
    { tagid: 4004, name: 'Retro' },
    { tagid: 4604, name: 'Dark Fantasy' },
    { tagid: 1651, name: 'Satire' },
    { tagid: 4085, name: 'Anime' },
    { tagid: 6378, name: 'Crime' },
    { tagid: 3916, name: 'Old School' },
    { tagid: 44868, name: 'LGBTQ+' },
    { tagid: 4695, name: 'Economy' },
    { tagid: 4853, name: 'Political' },
];

export const moods = [
    { tagid: 1654, name: 'Relaxing' },
    { tagid: 4136, name: 'Funny' },
    { tagid: 5608, name: 'Emotional' },
    { tagid: 5186, name: 'Psychological' },
    { tagid: 4342, name: 'Dark' },
    { tagid: 4145, name: 'Cinematic' },
    { tagid: 552282, name: 'Wholesome' },
    { tagid: 4726, name: 'Cute' },
    { tagid: 5984, name: 'Drama' },
    { tagid: 1714, name: 'Psychedelic' },
    { tagid: 5716, name: 'Mystery' },
    { tagid: 4667, name: 'Violent' },
];
