export const gameplayStyles = [
    'Action',
    'Stealth',
    'Turn-Based',
    'Building',
    'Procedural Generation',
    'Tactical',
    'Open World',
    'Sandbox',
    'Bullet Hell',
    'Walking Simulator',
    'Auto Battler',
    'Automation',
    'Choices Matter',
    'Exploration',
    'Deckbuilding',
    'Resource Management',
    'Arcade',
    'Narration',
    'Detective',
];

export const themes = [
    'Fantasy',
    'Magic',
    'Drama',
    'Surreal',
    'War',
    'Historical',
    'Cyberpunk',
    'Thriller',
    'Supernatural',
    'Mythology',
    'Noir',
    'Medieval',
    'Space',
    'Futuristic',
    'Dark',
    'Post-apocalyptic',
    'Western',
    'Superhero',
    'Sci-fi',
    'Romance',
    'Cute',
    'Retro',
    'Mystery',
    'Dark Fantasy',
    'Comedy',
];

export const moods = [
    'Atmospheric',
    'Relaxing',
    'Fast-Paced',
    'Casual',
    'Difficult',
    'Funny',
    'Emotional',
    'Psychological',
    'Violent',
];
