export const broadGenres = [
    'Simulation',
    'Strategy',
    'Adventure',
    'RPG',
    'Platformer',
    'Horror',
    'Survival',
    'Shooter',
    'FPS',
];

export const specificGenres = [
    'Puzzle',
    'Rogue-like',
    'Rogue-lite',
    'Turn-Based Strategy',
    'Dating Sim',
    'JRPG',
    'Card Game',
    'RTS',
    'Tower Defense',
    'Automobile Sim',
    'Rhythm',
    'Colony Sim',
    'MOBA',
    'Trivia',
    'Visual Novel',
    'Life Sim',
    'Board Game',
    'City Builder',
    "Beat 'em up",
    'Farming Sim',
    'Grand Strategy',
    'MMORPG',
    '4X',
    'Racing',
    'Battle Royale',
    'Sports',
    "Shoot 'Em Up",
    'Idler',
    'Metroidvania',
    'Hack and Slash',
    'Precision Platformer',
    'Souls-like',
    'Fighting',
    'Open World Survival Craft',
    'Management',
    'Survival Horror',
    '3D Platformer',
    'Party Game',
    'Party-Based RPG',
    'Hero Shooter',
];
