export const mainGenres = new Set([
    { id: 2, name: 'Point-and-click' },
    { id: 4, name: 'Fighting' },
    { id: 7, name: 'Music' },
    { id: 9, name: 'Puzzle' },
    { id: 10, name: 'Racing' },
    { id: 11, name: 'Real Time Strategy (RTS)' },
    { id: 12, name: 'Role-playing (RPG)' },
    { id: 13, name: 'Simulator' },
    { id: 14, name: 'Sport' },
    { id: 24, name: 'Tactical' },
    { id: 25, name: "Hack and slash/Beat 'em up" },
    { id: 33, name: 'Arcade' },
    { id: 34, name: 'Visual Novel' },
    { id: 35, name: 'Card & Board Game' },
]);

export const mainThemes = new Set([
    { id: 17, name: 'Fantasy' },
    { id: 18, name: 'Science fiction' },
    { id: 19, name: 'Horror' },
    { id: 20, name: 'Thriller' },
    { id: 21, name: 'Survival' },
    { id: 22, name: 'Historical' },
    { id: 31, name: 'Drama' },
    { id: 33, name: 'Sandbox' },
    { id: 38, name: 'Open world' },
    { id: 39, name: 'Warfare' },
    { id: 40, name: 'Party' },
    { id: 41, name: '4X (explore, expand, exploit, and exterminate)' },
    { id: 23, name: 'Stealth' },
    { id: 27, name: 'Comedy' },
    { id: 28, name: 'Business' },
    { id: 43, name: 'Mystery' },
    { id: 44, name: 'Romance' },
]);

export const mainKeywords = new Set([
    { id: 166, name: "shoot 'em up" },
    { id: 477, name: 'metroidvania' },
    { id: 521, name: 'jrpg' },
    { id: 840, name: 'cinematic' },
    { id: 131, name: 'psychological horror' },
    { id: 3533, name: 'city builder' },
    { id: 42080, name: 'idle' },
    { id: 17292, name: 'roguelite' },
    { id: 1836, name: 'survival horror' },
    { id: 12950, name: 'automation' },
    { id: 149, name: 'grand strategy' },
    { id: 25831, name: 'precision platforming' },
    { id: 25826, name: 'deck-building' },
    { id: 1103, name: 'farming' },
    { id: 510, name: 'crafting' },
    { id: 416, name: 'roguelike' },
    { id: 2231, name: '3d platformer' },
    { id: 77, name: 'tower defense' },
    { id: 1493, name: 'walking simulator' },
    { id: 17326, name: 'soulslike' },
    { id: 166, name: "shoot 'em up" },
    { id: 477, name: 'metroidvania' },
    { id: 521, name: 'jrpg' },
    { id: 840, name: 'cinematic' },
    { id: 131, name: 'psychological horror' },
    { id: 3533, name: 'city builder' },
    { id: 42080, name: 'idle' },
    { id: 17292, name: 'roguelite' },
    { id: 1836, name: 'survival horror' },
    { id: 12950, name: 'automation' },
    { id: 149, name: 'grand strategy' },
    { id: 25831, name: 'precision platforming' },
    { id: 25826, name: 'deck-building' },
    { id: 1103, name: 'farming' },
    { id: 510, name: 'crafting' },
    { id: 416, name: 'roguelike' },
    { id: 2231, name: '3d platformer' },
    { id: 77, name: 'tower defense' },
    { id: 1493, name: 'walking simulator' },
    { id: 17326, name: 'soulslike' },
    { id: 166, name: "shoot 'em up" },
    { id: 477, name: 'metroidvania' },
    { id: 521, name: 'jrpg' },
    { id: 840, name: 'cinematic' },
    { id: 131, name: 'psychological horror' },
    { id: 3533, name: 'city builder' },
    { id: 42080, name: 'idle' },
    { id: 17292, name: 'roguelite' },
    { id: 1836, name: 'survival horror' },
    { id: 12950, name: 'automation' },
    { id: 149, name: 'grand strategy' },
    { id: 25831, name: 'precision platforming' },
    { id: 25826, name: 'deck-building' },
    { id: 1103, name: 'farming' },
    { id: 510, name: 'crafting' },
    { id: 416, name: 'roguelike' },
    { id: 2231, name: '3d platformer' },
    { id: 77, name: 'tower defense' },
    { id: 1493, name: 'walking simulator' },
    { id: 17326, name: 'soulslike' },
]);
