export const mainGenres = [
    'roguelike',
    'roguelite',
    'metroidvania',
    'soulslike',
    `hack and slash/beat 'em up`,
    'music',
    `shoot 'em up`,
    'idle',
    'tower defense',
    '4x (explore, expand, exploit, and exterminate)',
    'real time strategy (rts)',
    'survival horror',
    'psychological horror',
    'precision platforming',
    'crafting',
    'farming',
    'point-and-click',
    'jrpg',
    'visual novel',
    '3d platformer',
    'open world',
    'puzzle',
    'sport',
    'simulator',
    'city builder',
    'racing',
    'romance',
    'automation',
    'card & board game',
    'quiz/trivia',
    'stealth',
    'walking simulator',
    'deck-building',
    'grand strategy',
    'cinematic',
    'fighting',
    'tactical',
    'arcade',
    'business',
];
