export const ownedGamesMock = [
    { appid: 400, name: 'portal', playtime: 522, recentlyPlayed: false },
    {
        appid: 12200,
        name: 'bully: scholarship edition',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 40800,
        name: 'super meat boy',
        playtime: 2885,
        recentlyPlayed: false,
    },
    {
        appid: 620,
        name: 'portal 2',
        playtime: 375,
        recentlyPlayed: false,
    },
    {
        appid: 105600,
        name: 'terraria',
        playtime: 73,
        recentlyPlayed: false,
    },
    { appid: 48000, name: 'limbo', playtime: 728, recentlyPlayed: false },
    {
        appid: 113200,
        name: 'the binding of isaac',
        playtime: 132,
        recentlyPlayed: false,
    },
    {
        appid: 108710,
        name: 'alan wake',
        playtime: 149,
        recentlyPlayed: false,
    },
    {
        appid: 219150,
        name: 'hotline miami',
        playtime: 1114,
        recentlyPlayed: false,
    },
    {
        appid: 227300,
        name: 'euro truck simulator 2',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 222480,
        name: 'resident evil revelations',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 236850,
        name: 'europa universalis iv',
        playtime: 6,
        recentlyPlayed: false,
    },
    {
        appid: 257850,
        name: 'hyper light drifter',
        playtime: 399,
        recentlyPlayed: false,
    },
    {
        appid: 268910,
        name: 'cuphead',
        playtime: 4567,
        recentlyPlayed: false,
    },
    {
        appid: 269210,
        name: 'hero siege',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 274170,
        name: 'hotline miami 2: wrong number',
        playtime: 438,
        recentlyPlayed: false,
    },
    {
        appid: 254700,
        name: 'resident evil 4 (2005)',
        playtime: 1312,
        recentlyPlayed: false,
    },
    {
        appid: 291860,
        name: 'pit people',
        playtime: 298,
        recentlyPlayed: false,
    },
    {
        appid: 247080,
        name: 'crypt of the necrodancer',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 322170,
        name: 'geometry dash',
        playtime: 88503,
        recentlyPlayed: true,
    },
    {
        appid: 730,
        name: 'counter-strike 2',
        playtime: 3154,
        recentlyPlayed: false,
    },
    {
        appid: 257510,
        name: 'the talos principle',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 250900,
        name: 'the binding of isaac: rebirth',
        playtime: 361,
        recentlyPlayed: false,
    },
    {
        appid: 304240,
        name: 'resident evil',
        playtime: 2019,
        recentlyPlayed: false,
    },
    {
        appid: 346900,
        name: 'adventure capitalist',
        playtime: 3075,
        recentlyPlayed: false,
    },
    {
        appid: 287290,
        name: 'resident evil revelations 2',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 255710,
        name: 'cities: skylines',
        playtime: 81,
        recentlyPlayed: false,
    },
    {
        appid: 356670,
        name: "spooky's jump scare mansion",
        playtime: 244,
        recentlyPlayed: false,
    },
    {
        appid: 297130,
        name: 'titan souls',
        playtime: 257,
        recentlyPlayed: false,
    },
    {
        appid: 367520,
        name: 'hollow knight',
        playtime: 4647,
        recentlyPlayed: false,
    },
    {
        appid: 292030,
        name: 'the witcher 3: wild hunt',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 261570,
        name: 'ori and the blind forest',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 387290,
        name: 'ori and the blind forest: definitive edition',
        playtime: 320,
        recentlyPlayed: false,
    },
    {
        appid: 394360,
        name: 'hearts of iron iv',
        playtime: 28217,
        recentlyPlayed: false,
    },
    {
        appid: 395170,
        name: 'distraint: deluxe edition',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 413150,
        name: 'stardew valley',
        playtime: 2102,
        recentlyPlayed: false,
    },
    {
        appid: 339340,
        name: 'resident evil 0',
        playtime: 228,
        recentlyPlayed: false,
    },
    {
        appid: 428550,
        name: 'momodora: reverie under the moonlight',
        playtime: 899,
        recentlyPlayed: false,
    },
    {
        appid: 431730,
        name: 'aseprite',
        playtime: 7908,
        recentlyPlayed: true,
    },
    {
        appid: 391220,
        name: 'rise of the tomb raider',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 433340,
        name: 'slime rancher',
        playtime: 256,
        recentlyPlayed: false,
    },
    {
        appid: 460950,
        name: 'katana zero',
        playtime: 689,
        recentlyPlayed: false,
    },
    {
        appid: 504230,
        name: 'celeste',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 508440,
        name: 'totally accurate battle simulator',
        playtime: 1871,
        recentlyPlayed: false,
    },
    {
        appid: 289070,
        name: "sid meier's civilization vi",
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 418370,
        name: 'resident evil 7 biohazard',
        playtime: 877,
        recentlyPlayed: false,
    },
    {
        appid: 557340,
        name: 'my friend pedro',
        playtime: 165,
        recentlyPlayed: false,
    },
    {
        appid: 557600,
        name: 'gorogoa',
        playtime: 99,
        recentlyPlayed: false,
    },
    {
        appid: 583470,
        name: 'the end is nigh',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 588650,
        name: 'dead cells',
        playtime: 445,
        recentlyPlayed: false,
    },
    {
        appid: 632470,
        name: 'disco elysium',
        playtime: 1989,
        recentlyPlayed: true,
    },
    {
        appid: 644560,
        name: 'mirror',
        playtime: 146,
        recentlyPlayed: false,
    },
    {
        appid: 650700,
        name: 'yume nikki',
        playtime: 0,
        recentlyPlayed: false,
    },
    { appid: 683320, name: 'gris', playtime: 185, recentlyPlayed: false },
    {
        appid: 698780,
        name: 'doki doki literature club',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 240720,
        name: 'getting over it with bennett foddy',
        playtime: 12329,
        recentlyPlayed: true,
    },
    {
        appid: 718590,
        name: 'dark devotion',
        playtime: 26,
        recentlyPlayed: false,
    },
    {
        appid: 753640,
        name: 'outer wilds',
        playtime: 16,
        recentlyPlayed: false,
    },
    {
        appid: 774171,
        name: 'muse dash',
        playtime: 278,
        recentlyPlayed: false,
    },
    {
        appid: 774361,
        name: 'blasphemous',
        playtime: 1514,
        recentlyPlayed: false,
    },
    {
        appid: 787480,
        name: 'phoenix wright: ace attorney trilogy',
        playtime: 2010,
        recentlyPlayed: false,
    },
    {
        appid: 570940,
        name: 'dark souls™: remastered',
        playtime: 1226,
        recentlyPlayed: false,
    },
    {
        appid: 848450,
        name: 'subnautica: below zero',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 871720,
        name: 'ultimate custom night',
        playtime: 916,
        recentlyPlayed: false,
    },
    {
        appid: 883710,
        name: 'resident evil 2',
        playtime: 2239,
        recentlyPlayed: false,
    },
    {
        appid: 764790,
        name: 'the messenger',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 960090,
        name: 'bloons td 6',
        playtime: 6529,
        recentlyPlayed: false,
    },
    {
        appid: 1057090,
        name: 'ori and the will of the wisps',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 1061090,
        name: 'jump king',
        playtime: 787,
        recentlyPlayed: false,
    },
    {
        appid: 1092790,
        name: 'inscryption',
        playtime: 316,
        recentlyPlayed: false,
    },
    {
        appid: 1097150,
        name: 'fall guys',
        playtime: 160,
        recentlyPlayed: false,
    },
    {
        appid: 1147560,
        name: 'skul: the hero slayer',
        playtime: 63,
        recentlyPlayed: false,
    },
    {
        appid: 1174180,
        name: 'red dead redemption 2',
        playtime: 2506,
        recentlyPlayed: false,
    },
    {
        appid: 505230,
        name: 'pathologic 2',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 1145360,
        name: 'hades',
        playtime: 1335,
        recentlyPlayed: false,
    },
    {
        appid: 322500,
        name: 'superhot',
        playtime: 335,
        recentlyPlayed: false,
    },
    {
        appid: 12210,
        name: 'grand theft auto iv: the complete edition',
        playtime: 108,
        recentlyPlayed: false,
    },
    {
        appid: 1276390,
        name: 'bloons td battles 2',
        playtime: 18608,
        recentlyPlayed: false,
    },
    {
        appid: 435790,
        name: '10 second ninja x',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 1367590,
        name: 'tormented souls',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 1454400,
        name: 'cookie clicker',
        playtime: 33621,
        recentlyPlayed: false,
    },
    {
        appid: 1235140,
        name: 'yakuza: like a dragon',
        playtime: 599,
        recentlyPlayed: false,
    },
    {
        appid: 1604000,
        name: 'milk outside a bag of milk outside a bag of milk',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 264710,
        name: 'subnautica',
        playtime: 2178,
        recentlyPlayed: false,
    },
    {
        appid: 1245620,
        name: 'elden ring',
        playtime: 8964,
        recentlyPlayed: false,
    },
    {
        appid: 1850570,
        name: "death stranding director's cut",
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 1196590,
        name: 'resident evil village',
        playtime: 2018,
        recentlyPlayed: false,
    },
    {
        appid: 1236300,
        name: 'resident evil re:verse',
        playtime: 0,
        recentlyPlayed: false,
    },
    {
        appid: 529340,
        name: 'victoria 3',
        playtime: 33,
        recentlyPlayed: false,
    },
    {
        appid: 2050650,
        name: 'resident evil 4',
        playtime: 2816,
        recentlyPlayed: false,
    },
    {
        appid: 2231450,
        name: 'pizza tower',
        playtime: 3836,
        recentlyPlayed: false,
    },
    {
        appid: 1086940,
        name: "baldur's gate 3",
        playtime: 0,
        recentlyPlayed: false,
    },
];
